import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  {
    ignores: [
      // The marketing site is its own Next app with its own config; linting it
      // from here would apply the CRM's rules to a tree that never sees them.
      "website/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by the PWA plugin at build time; see .gitignore.
      "public/sw.js",
      "public/workbox-*.js",
      "public/fallback-*.js",
      "public/swe-worker-*.js",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
